name: Test
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout your project with git
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5

      - name: Prepare tparse
        run: |
          go install github.com/mfridman/tparse@latest

      - name: Run tests
        run: |
          go test ./... -json -cover | tee ./go-test.out | tparse -all

      - name: Add Summary
        run: |
          tparse -file ./go-test.out -all -format markdown >> $GITHUB_STEP_SUMMARY
